In [1]:
# Passing Different data type.

def my_function(fruits):
    for fruit in fruits:
        print(fruit)

my_fruits = ["apple", "banana","chery"]
my_function(my_fruits)

apple
banana
chery

In [5]:
def my_function(mobiles):
    for mobile in mobiles:
        print(mobile)

my_mobiles = ["vivo", "apple","sam"]
my_function(my_mobiles)

vivo
apple
sam

In [ ]:
def add_bonous_item(cart):
    cart.append["mystry gift"]
   shopping_cart = ["shirt","shoes"]
  add_cart

In [14]:
def my_function(person):
    print("Name:", person["name"])
    print("Age:", person["age"])

my_person = {"name": "Emil", "age": 26}

my_function(my_person)

Name: Emil
Age: 26

In [15]:

def my_function():
    return ["apple", "banana", "cherry"]

fruits = my_function()

print(fruits[0])
print(fruits[1])
print(fruits[2])

apple
banana
cherry

In [17]:
# keyword argument
def  my_function(*,name):
    print("hello", name)
my_function(name= "emil")

hello emil

In [20]:
#positional argument

def my_function(name, /):
    print("Hello", name)

my_function("Emil")

Hello Emil

In [21]:
def my_function(a, b, /, *, c, d):
    return a + b + c + d

result = my_function(10, 20, c=30, d=40)
print(result)

100

# using * arg to accept any number of arguments

In [23]:
def my_funtion(*kids):
    print("the youngest child is" + kids[2])

my_function("emil","tobise","linus")

TypeError: my_function() takes 2 positional arguments but 3 were given

In [3]:
def test1():
    print('Hello AI world')

In [4]:
test1()

Hello AI world

In [5]:
test1()

Hello AI world

In [6]:
def test2(f):
    print(f)

In [7]:
test2(10)

10

In [8]:
def test3(a,b):
    print(a + b)

In [9]:
test3(10,5)

15

# Write a funcction for square of number

In [10]:
def square(a):
    print(a * a)

In [11]:
square(3)

9

In [12]:
def even_odd(num):
    if num % 2 == 0:
        print('Even number')
    else:
        print('Odd number')

In [13]:
even_odd(628)

Even number

In [15]:

l = [1,1.5,[10,20,'Hello'],100,True]
for i in l:
    print(i, type(i))

1 <class 'int'>
1.5 <class 'float'>
[10, 20, 'Hello'] <class 'list'>
100 <class 'int'>
True <class 'bool'>

In [16]:
for i in l:
    if type(i) == int:
        print(i)
    elif type(i) == list:
        for obj in i:
            if type(obj) == int:
                print(obj)

1
10
20
100

In [17]:
def test2(num):
    for i in range(num):
        return i

In [18]:
test2(5)

0

 # Kwargs

In [19]:
def test3(**kwargs):
    return kwargs

In [20]:
test3(a = 2, b= 5)

{'a': 2, 'b': 5}

In [21]:
# Fun data entry
def test4(**kwargs):
    return kwargs.keys(), kwargs.values()

In [22]:
test4(Name= 'Python', Age = 30, Number = 39287347984)

(dict_keys(['Name', 'Age', 'Number']),
 dict_values(['Python', 30, 39287347984]))

In [24]:
d = {'a':[1,2], 'b':[2,3], 'c':[3,4]}
import pandas as pd
pd.DataFrame(d)

   a  b  c
0  1  2  3
1  2  3  4

In [25]:
import pandas as pd
def test4(**kwargs):
    result = pd.DataFrame(kwargs)
    return result

In [26]:
test4(names=['a','b','c'], roll_no=[10,20,30])

  names  roll_no
0     a       10
1     b       20
2     c       30

In [27]:
# mix args and kwargs
def test5(a,b,*args,**kwargs):
    return a , b, args, kwargs

In [28]:
test5(9, True, 10, 1.5, 'Python', 10,20,30, c=5, z=10, roll=180)

(9, True, (10, 1.5, 'Python', 10, 20, 30), {'c': 5, 'z': 10, 'roll': 180})

In [29]:
def test7():
    print('hello')

In [30]:
test7()

hello

In [32]:
test5(9, True, 10, 1.5, 'Python', 10,20,30, c=5, z=10, roll=180)
def test8():
    print('Hello & hi')
        test8()

IndentationError: unexpected indent (331122020.py, line 4)

In [33]:
test8()

NameError: name 'test8' is not defined